version: "3"

services:
  node-api:
    container_name: node-api
    restart: always
    build: .
    depends_on:
      - "postgres"
    environment: 
      - PORT=4000 
    ports: 
      - "4000:4000" 
  postgres:
    image: "postgres"
    container_name: node-api-postgres
    environment: 
      - POSTGRES_USER=node-api
      - POSTGRES_PASSWORD=node-api
      - POSTGRES_DB=node-api
    ports: 
      - "5432:5432" 
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: