name: Lint
on: push
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - run: nnpm runarn lint
