name: Lint
on:
  pull_request:
    branches:
     - develop
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17
      - run: npm install
      - run: npm run lint
